version: '3.8'
services:
  app:
    container_name: electronic-store
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SERVER_PORT=8080
      - SERVER_ADDRESS=0.0.0.0
    networks:
      - store-network

networks:
  store-network:
    driver: bridge 